admin/controllers/VerifikasiOrganizerController.php
<?php

namespace admin\controllers;
use admin\models\OrganizerVerificationSearch;
use Carbon\Carbon;
use common\models\Notification;
use common\models\StatusKonten;
use common\models\UserOrganizer;
use dosamigos\google\maps\LatLng;
use dosamigos\google\maps\Map;
use dosamigos\google\maps\overlays\Marker;
use organizer\models\NotificationOrganizer;
use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class VerifikasiOrganizerController extends Controller
{
    public function behaviors(){

        return[
            'verbs'=>[
                'class'=> VerbFilter::class,
                'actions'=>[
                    'delete'=>['POST'],
                    'approve'=>['POST'],
                    'reject'=>['POST']
                ]
            ]
        ];
    }

    public function actionIndex(){
        $searchModel = new OrganizerVerificationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }
    public function actionView($id){

        $model = $this->findModel($id);
        $verificationData = new OrganizerVerificationSearch();
        $dataProvider = $verificationData->verificationData($id);
        $location = new LatLng(['lat'=>$model->latitude, 'lng'=>$model->longitude]);
        $map = new Map([
            'center'=>$location,
            'zoom'=>15
        ]);
        $marker = new Marker([
            'position'=>$location,
            'title'=> $model->name
        ]);
        $map->addOverlay($marker);
        return $this->render('view',['model'=>$model,'map'=>$map,'dataProvider'=>$dataProvider]);
    }

    public function actionApprove($id){
        $modelOrganizer = $this->findModel($id);
        $modelOrganizer->setIsVerified(StatusKonten::STATUS_VERIFIED);
        $modelOrganizer->setVerificationStatus(StatusKonten::ORGANIZER_VERIFIED);
        $modelOrganizer->save(false);
        $this->sendNotification($id,'success');
        Yii::$app->getSession()->setFlash('success','Berhasil Verifikasi Organizer');
        return $this->redirect('index');


    }

    public function actionReject($id){
        $modelOrganizer = $this->findModel($id);
        $modelOrganizer->setIsVerified(StatusKonten::STATUS_NOT_VERIFIED);
        $modelOrganizer->setVerificationStatus(StatusKonten::ORGANIZER_NOT_VERIFIED);
        $modelOrganizer->save(false);
        $this->sendNotification($id,'failed');
        Yii::$app->getSession()->setFlash('success','Verifikasi Organizer Ditolak');
        return $this->redirect('index');
    }

    protected function findModel($id){
        if( ($model = UserOrganizer::findOne($id)) !=null){
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');

    }


    /**
     * @param $id
     * @param $status
     * @return mixed
     */
    protected function sendNotification($id, $status){
        $notification = new Notification();
        $modelNotif = new NotificationOrganizer();

        $notification->from = 'Admin Event-Hub';
        $notification->time = Carbon::now()->timestamp;
        $notification->urlAction = Yii::$app->urlManagerOrganizer->createAbsoluteUrl(['notification/index']);
        $notification->image = 'info';
        switch ($status){
            case 'success': $notification->message = 'Permintaan verifikasi anda telah disetujui.'; break;
            case 'failed': $notification->message = 'Permintaan verifikasi anda ditolak, silahkan ajukan kembali'; break;
        }

        $modelNotif->channel = Yii::$app->webPusher->getOrganizerChannelName($id);
        $modelNotif->event = 'notification';
        $modelNotif->action = $notification->urlAction;
        $modelNotif->organizer = $id;
        $modelNotif->messages = $notification->message;
        $modelNotif->from = $notification->from;
        $modelNotif->created_at = $notification->time;
        $modelNotif->updated_at = $notification->time;
       return Yii::$app->webPusher->pushToOrganizer($notification->encode(), $id);


    }


}

admin/views/verifikasi-organizer/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel admin\models\BankSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Verifikasi Organizer';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-12">
        <div class="card-box">
            <div class="card-content">
                <h4 class="header-title m-t-0 m-b-30"><?= Html::encode($this->title) ?></h4>
                <div class="row">
                    <div class="col-md-12">
                        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
                        <?= GridView::widget([
                            'dataProvider' => $dataProvider,
                            'filterModel' => $searchModel,
                            'columns' => [
                                ['class' => 'yii\grid\SerialColumn', 'header' => 'No'],

                                //'id',
                                'name',
                                'organization.name',
                                'isVerified:boolean',
                                'verification_status',
//                                'isDeleted:boolean',
//                                'created_at:datetime',
//                                'updated_at:datetime',

                                ['class' => 'yii\grid\ActionColumn', 'header' => 'Aksi',
                                    'template'=> '{view}',
                                    'buttons'=>[
                                            'view' => function ($url,$model){
                                            return Html::a('<i class="zmdi zmdi-eye"></i>',\yii\helpers\Url::to(['verifikasi-organizer/view','id'=>$model->id]));
                                            }
                                    ]],
                            ],
                        ]); ?>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

admin/views/verifikasi-organizer/view.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Type */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Verifikasi Organizer', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="type-view">

    <div class="row">
        <div class="col-md-12">
            <div class="card-box">
                <div class="card-content">
                    <h4 class="header-title m-t-0 m-b-30"><?= Html::encode($this->title) ?></h4>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="text-center">
                                <?=Html::img(Yii::getAlias('@organizerImage/avatar/'.$model->profile_picture),['class'=>'mx-auto d-block', 'height'=>200, 'width'=>200])?>
                                <h4 class="m-t-0 m-b-30"><?= Html::encode($this->title) ?></h4>
                                <p>Description:</p><?=\yii\helpers\HtmlPurifier::process($model->description)?>
                            </div>


                            <?=$map->display()?>
                        </div>
                        <div class="col-md-6">

                            <?= DetailView::widget([
                                'model' => $model,
                                'attributes' => [
                                    'id',
                                    'email:email',
//                                    'password_hash',
                                    'name',
                                    'organization.name',
                                    'address_1',
                                    'address_2',
                                    'country',
                                    'province',
                                    'city',
                                    'postal_code',
                                    'latitude',
                                    'longitude',

                                    'work_phone',
                                    'cell_phone',
                                    'description',
                                    'twitter',
                                    'instagram',
                                    'facebook',
                                    'whatsapp',
                                    'website',
                                    'bank.name',
                                    'bank_account',
                                    'isDeleted:boolean',
                                    'created_at:datetime',
                                    'updated_at:datetime',
                                    'auth_key',
                                    'access_token',
                                    'isVerified:boolean',
                                    'verification_status',
                                ],
                            ]) ?>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card-box">

                <h4 class="header-title m-t-0 m-b-30">Verification File</h4>
                <p>
                    <?= Html::a('<span><i class="zmdi zmdi-check"></i> </span>Setujui', ['approve', 'id' => $model->id], ['class' => 'btn btn-success waves-effect waves-light', 'data' => [
                        'confirm' => 'Anda yakin untuk Menerima permintaan ini?',
                        'method'=>'POST'
                    ],]) ?>
                    <?= Html::a('<span><i class="zmdi zmdi-delete"></i> </span>Tolak', ['reject', 'id' => $model->id], [
                        'class' => 'btn btn-danger waves-effect waves-light',
                        'data' => [
                            'confirm' => 'Anda yakin untuk menolak permintaan ini?',
                            'method'=>'POST'
                        ],
                    ]) ?>
                </p>
                <div class="card-content">
                    <?= GridView::widget([
                            'dataProvider' => $dataProvider,
                            'columns' => [
                                ['class' => 'yii\grid\SerialColumn', 'header' => 'No'],

                                //'id',
                                [
                                    'attribute'=>'verification_file',
                                    'value'=>function($model){
                                        $url = Yii::getAlias('@organizerUpload/verification/'.$model->verification_file);
                                        return Html::a($model->verification_file,\yii\helpers\Url::to($url), ['target' => '_blank']);
                                    },
                                    'format'=>'raw'
                                ],

//                                'isDeleted:boolean',
//                                'created_at:datetime',
//                                'updated_at:datetime',

                            ]
                        ]

                    ); ?>
                </div>

            </div>
        </div>
    </div>

</div>