admin/controllers/NotificationController.php
<?php
/**
 * Project: event-hub.
 * @author Adryan Eka Vandra <adryanekavandra@gmail.com>
 *
 * Date: 2/12/2019
 * Time: 5:00 PM
 */

namespace admin\controllers;


use admin\models\NotificationAdmin;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;

class NotificationController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
        ];
    }

    public function actionIndex(){
        $model = NotificationAdmin::find()->orderBy('created_at desc')->all();
        return $this->render('index',['notifications'=>$model]);

    }
}

admin/views/layouts/content.php
<?php
/**
 * Created by PhpStorm.
 * User: adryanev
 * Date: 25/01/18
 * Time: 13:45
 */
use yii\widgets\Breadcrumbs;
?>

<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?php echo \yii2mod\alert\Alert::widget([
                'useSessionFlash' => true,
            ]);?>
            <?=$content?>
        </div> <!-- container -->
    </div> <!-- content -->

admin/views/layouts/footer.php
<?php
/**
 * Created by PhpStorm.
 * User: adryanev
 * Date: 25/01/18
 * Time: 13:46
 */?>

<footer class="footer text-right">
    &copy; <script>document.write(new Date().getFullYear())</script> Adryan Eka Vandra.
</footer>
</div>
<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->

admin/views/layouts/header.php
<?php
/**
 * Created by PhpStorm.
 * User: adryanev
 * Date: 25/01/18
 * Time: 13:44
 */

use yii\helpers\Html;
$route = $this->context->route;
$controllerName = substr($route,0,strpos($route,'/'));
if($controllerName == 'site'){
    $controllerName = "Dashboard";
}
?>
<!-- Begin page -->
<div id="wrapper">

    <!-- Top Bar Start -->
    <div class="topbar">

        <!-- LOGO -->
        <div class="topbar-left">
            <a href="<?=Yii::$app->urlManager->getBaseUrl()?>" class="logo"><span>Beranda<span>Admin</span></span><i class="zmdi zmdi-layers"></i></a>
        </div>

        <!-- Button mobile view to collapse sidebar menu -->
        <div class="navbar navbar-default" role="navigation">
            <div class="container">

                <!-- Page title -->
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <button class="button-menu-mobile open-left">
                            <i class="zmdi zmdi-menu"></i>
                        </button>
                    </li>
                    <li>
                        <h4 class="page-title"><?=ucwords($controllerName)?></h4>
                    </li>
                </ul>

                <!-- Right(Notification and Searchbox -->
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <!-- Notification -->
                        <div class="notification-box">
                            <ul class="list-inline m-b-0">
                                <li>
                                    <a href="javascript:void(0);" class="right-bar-toggle">
                                        <i class="zmdi zmdi-notifications-none"></i>
                                    </a>
                                    <div class="noti-dot">
                                        <span class="dot"></span>
                                        <span class="pulse"></span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <!-- End Notification bar -->
                    </li>
                    <li class="hidden-xs">
                        <form role="search" class="app-search">
                            <input type="text" placeholder="Search..."
                                   class="form-control">
                            <a href=""><i class="fa fa-search"></i></a>
                        </form>
                    </li>
                </ul>

            </div>
            <!-- end container -->
        </div><!-- end navbar -->
    </div>
    <!-- Top Bar End -->

admin/views/layouts/main-login.php
<?php
/**
 * Created by PhpStorm.
 * User: adryanev
 * Date: 08/02/18
 * Time: 10:19
 */

use admin\assets\AppAsset;
use yii\helpers\Html;
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>


        <?= $content ?>



<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

admin/views/layouts/main-not-found.php
<?php
/**
 * Created by PhpStorm.
 * User: adryanev
 * Date: 08/02/18
 * Time: 10:19
 */

use admin\assets\AppAsset;
use yii\helpers\Html;
AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>


<?= $content ?>



<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

admin/views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use admin\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\web\View;


AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="fixed-left">
<?php $this->beginBody() ?>
<?= \common\widgets\PusherWidget::widget(['events' => [
    'notification'],
    'system'=>['admin']]) ?>
<?= $this->render('header') ?>
<?= $this->render('sidebar') ?>
<?= $this->render('content', ['content' => $content]) ?>
<?= $this->render('footer') ?>
<?= $this->render('right-sidebar')?>

<?php $this->endBody() ?>



<script type="text/javascript">
    function showNotification(data) {
        const notification = document.getElementById('notif-list');

        lowLag.init();
        const notifSound = '<?= Yii::getAlias('@web/sounds/dont-think-so.ogg')?>';
        const url = 'http://admin.event-hub.com/verifikasi-organizer/';
        lowLag.load(notifSound);

        lowLag.play(notifSound);
        console.log(data);
        let html = "<li class=\"list-group-item\">\n" +
            "                    <a href=\""+url+"\" class=\"user-list-item\">\n" +
            "                        <div class=\"icon bg-info\">\n" +
            "                            <i class=\"zmdi zmdi-comment\"></i>\n" +
            "                        </div>\n" +
            "                        <div class=\"user-desc\">\n" +
            "                            <span class=\"name\">"+data.from+"</span>\n" +
            "                            <span class=\"desc\">"+data.message+"</span>\n" +
            "                            <span class=\"time\">"+data.time+"</span>\n" +
            "                        </div>\n" +
            "                    </a>\n" +
            "                </li>";
        notification.insertAdjacentHTML('afterbegin',html)

        let counter = -1;
        let toastCounter = 0;
        let lastToast;

        const notifType = 'info';
        const message = data.message;
        const title= data.from;

        lastToast = toastr[notifType](message, title);

        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": true,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };


        function getLastToast() {
            return lastToast;

        }
        $('#clearlasttoast').click(function () {
            toastr.clear(getLastToast());
        });
        $('#cleartoasts').click(function () {
            toastr.clear();
        });
    }

</script>
</body>
</html>
<?php $this->endPage() ?>

admin/views/layouts/right-sidebar.php
<?php
/**
 * Project: event-hub.
 * @author Adryan Eka Vandra <adryanekavandra@gmail.com>
 *
 * Date: 1/26/2019
 * Time: 1:45 AM
 */

?>


<!-- Right Sidebar -->
<div class="side-bar right-bar">

    <a href="javascript:void(0);" class="right-bar-toggle">
        <i class="zmdi zmdi-close-circle-o"></i>
    </a>
    <h4 class="">Notifications</h4>
    <?= \yii\helpers\Html::a('<h6>Lihat semua notifikasi</h6>',\yii\helpers\Url::to(['notification/index']))?>



    <div class="notification-list nicescroll">
        <ul class="list-group list-no-border user-list" id="notif-list">

            <?php
            $notifs = \admin\models\NotificationAdmin::find()->where(['isDeleted' => 0])->orderBy('created_at desc')->limit(10)->all();

            foreach ($notifs as $item):
                if($item->event === 'organizer-verification-event'):
               ?>

                <li class="list-group-item">
                    <a href="<?=\yii\helpers\Url::to(['verifikasi-organizer/index'])?>" class="user-list-item">
                        <div class="icon bg-info">
                            <i class="zmdi zmdi-comment"></i>
                        </div>
                        <div class="user-desc">
                            <span class="name"><?=$item->from?></span>
                            <span class="desc"><?= $item->messages?></span>
                            <span class="time"><?= \Carbon\Carbon::createFromTimestamp($item->created_at)->diffForHumans()?></span>
                        </div>
                    </a>
                </li>
            <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<!-- /Right-bar -->

</div>
<!-- END wrapper -->

<script>
    var resizefunc = [];
</script>

admin/views/layouts/sidebar.php
<?php
/**
 * Created by PhpStorm.
 * User: adryanev
 * Date: 25/01/18
 * Time: 13:44
 */

use yii\helpers\Html;
$route = $this->context->route;
$controllerName = substr($route,0,strpos($route,'/'));

?>
<!-- ========== Left Sidebar Start ========== -->
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!-- User -->
        <div class="user-box">
            <div class="user-img">

                <img src="<?=Yii::getAlias("@web/images/avatar/").Yii::$app->user->identity->profile_picture?>" alt="user-img" title="Mat Helme" class="img-circle img-thumbnail img-responsive">
                <div class="user-status online"><i class="zmdi zmdi-dot-circle"></i></div>
            </div>
            <h5><a href="#"><?= Yii::$app->user->identity->getFullName() ?></a> </h5>
            <ul class="list-inline">
                <li>
                    <?= Html::a(' <i class="zmdi zmdi-settings"></i>',\yii\helpers\Url::to(['admin/view']),['class'=> 'btn btn-link']) ?>
                </li>

                <li>
                    <?=Html::beginForm(['/site/logout'], 'post');?>
                    <?=Html::submitButton(' <i class="zmdi zmdi-power"></i>', ['class' => 'btn btn-link logout','data' => [
                            'confirm' => 'Apakah anda ingin keluar?',
                            ]]
                    );?>
                    <?=Html::endForm();?>
                </li>
            </ul>
        </div>
        <!-- End User -->


        <!--- Sidemenu -->

        <div id="sidebar-menu">
            <ul>
                <li class="text-muted menu-title">Navigation</li>
            </ul>

            <?= \common\widgets\Menu::widget(
                    [
                        'items' => [
                            ['label'=>'Beranda', 'icon'=>'zmdi-view-dashboard','url'=>['/site'],'template'=>$controllerName === 'site'? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Topik Event', 'icon'=>'zmdi-view-list','url'=>['/topic'],'template'=>$controllerName === 'topic' ? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Tipe Event', 'icon'=>'zmdi-format-list-bulleted','url'=>['/type'],'template'=>$controllerName === 'type' ? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Bank', 'icon'=>'zmdi-local-atm','url'=>['/bank'],'template'=>$controllerName === 'bank'? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Event Status', 'icon'=>'zmdi-format-list-bulleted','url'=>['/event-status'],'template'=>$controllerName === 'event-status' ? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Organisasi', 'icon'=>'zmdi-accounts-list','url'=>['/organization'],'template'=>$controllerName === 'organization' ? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Metode Pembayaran', 'icon'=>'zmdi-card','url'=>['/payment-method'],'template'=>$controllerName === 'payment-method' ? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Pengguna', 'icon'=>'zmdi-account-circle','url'=>['/pengguna'],'template'=>$controllerName === 'admin'? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Organizer', 'icon'=>'zmdi-accounts','url'=>['/organizer'],'template'=>$controllerName === 'admin'? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Verifkasi Organizer', 'icon'=>'zmdi-file-text','url'=>['/verifikasi-organizer'],'template'=>$controllerName === 'admin'? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Pembayaran', 'icon'=>'zmdi-money','url'=>['/pembayaran'],'template'=>$controllerName === 'admin'? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Pengembalian', 'icon'=>'zmdi-money-off','url'=>['/pengembalian'],'template'=>$controllerName === 'admin'? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Pencairan', 'icon'=>'zmdi-money-box','url'=>['/pencairan'],'template'=>$controllerName === 'admin'? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Wallet Pengguna', 'icon'=>'zmdi-balance-wallet','url'=>['/pencairan'],'template'=>$controllerName === 'admin'? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'Wallet Organizer', 'icon'=>'zmdi-balance','url'=>['/pencairan'],'template'=>$controllerName === 'admin'? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],
                            ['label'=>'API', 'icon'=>'zmdi-code','url'=>['/api'],'template'=>$controllerName === 'admin'? '<a href="{url}" class="waves-effect active">{icon} {label}</a>': '<a href="{url}" class="waves-effect">{icon} {label}</a>'],

                        ]
                    ]

            ) ?>

        </div>
        <div class="clearfix"></div>

    </div>

</div>
<!-- Left Sidebar End -->

admin/views/layouts/signup.php
<?php
/**
 * Created by PhpStorm.
 * User: adryanev
 * Date: 25/01/18
 * Time: 13:47
 */